(function(){var aa=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},d=ba(this),m=function(a,b){if(b)a:{var c=d;a=a.split(".");for(var e=0;e<a.length-
1;e++){var f=a[e];if(!(f in c))break a;c=c[f]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&b!=null&&aa(c,a,{configurable:!0,writable:!0,value:b})}};m("globalThis",function(a){return a||d});
m("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var n=this||self,p=function(a,b){a=a.split(".");for(var c=n,e;a.length&&(e=a.shift());)a.length||b===void 0?c[e]&&c[e]!==Object.prototype[e]?c=c[e]:c=c[e]={}:c[e]=b};var q=new Map([]);q.set("android-fully-clickable",{src:"/codelabs/js/devsite_android_fully_clickable_module.js"});q.set("cloud-mdc-rich-tooltip",{src:"/codelabs/js/devsite_cloud_mdc_rich_tooltip_module.js"});q.set("cloud-shell-button",{src:"/codelabs/js/devsite_cloud_shell_button_module.js"});q.set("cloud-shell-pane",{src:"/codelabs/js/devsite_cloud_shell_pane_module.js"});q.set("cloudx-chat",{src:"/codelabs/js/devsite_cloudx_chat_module.js"});q.set("devsite-a11y-announce",{src:"/codelabs/js/devsite_devsite_a11y_announce_module.js"});
q.set("devsite-activity-tracker",{src:"/codelabs/js/devsite_devsite_activity_tracker_module.js"});q.set("devsite-analytics",{src:"/codelabs/js/devsite_devsite_analytics_module.js"});q.set("devsite-analytics-scope",{src:"/codelabs/js/devsite_devsite_analytics_scope_module.js"});q.set("devsite-anselm",{src:"/codelabs/js/devsite_devsite_anselm_module.js"});q.set("devsite-api-getstarted",{src:"/codelabs/js/devsite_devsite_api_getstarted_module.js"});q.set("devsite-apix",{src:"/codelabs/js/devsite_devsite_apix_module.js"});
q.set("devsite-apix-index",{src:"/codelabs/js/devsite_devsite_apix_index_module.js"});q.set("devsite-apix-snippets",{src:"/codelabs/js/devsite_devsite_apix_snippets_module.js"});q.set("devsite-appearance-selector",{src:"/codelabs/js/devsite_devsite_appearance_selector_module.js"});q.set("devsite-author-page-insights",{src:"/codelabs/js/devsite_devsite_author_page_insights_module.js"});q.set("devsite-badge-awarded",{src:"/codelabs/js/devsite_devsite_badge_awarded_module.js"});
q.set("devsite-badge-awarder",{src:"/codelabs/js/devsite_devsite_badge_awarder_module.js"});q.set("devsite-badge-redeemer",{src:"/codelabs/js/devsite_devsite_badge_redeemer_module.js"});q.set("devsite-badger",{src:"/codelabs/js/devsite_devsite_badger_module.js"});q.set("devsite-book-nav",{src:"/codelabs/js/devsite_devsite_book_nav_module.js"});q.set("devsite-bookmark",{src:"/codelabs/js/devsite_devsite_bookmark_module.js"});q.set("devsite-carousel",{src:"/codelabs/js/devsite_devsite_carousel_module.js"});
q.set("devsite-catalog",{src:"/codelabs/js/devsite_devsite_catalog_module.js"});q.set("devsite-catalog-body-badges",{src:"/codelabs/js/devsite_devsite_catalog_body_badges_module.js"});q.set("devsite-chart",{src:"/codelabs/js/devsite_devsite_chart_module.js"});q.set("devsite-chat-spark-button",{src:"/codelabs/js/devsite_devsite_chat_spark_button_module.js"});q.set("devsite-checkbox",{src:"/codelabs/js/devsite_devsite_checkbox_module.js"});q.set("devsite-chip",{src:"/codelabs/js/devsite_devsite_chip_module.js"});
q.set("devsite-code",{src:"/codelabs/js/devsite_devsite_code_module.js"});q.set("devsite-code-tutorial",{src:"/codelabs/js/devsite_devsite_code_tutorial_module.js"});q.set("devsite-codelab-catalog",{src:"/codelabs/js/devsite_devsite_codelab_catalog_module.js"});q.set("devsite-concierge",{src:"/codelabs/js/devsite_devsite_concierge_module.js"});q.set("devsite-concierge-ai-panel",{src:"/codelabs/js/devsite_devsite_concierge_ai_panel_module.js"});q.set("devsite-concierge-api-explorer-panel",{src:"/codelabs/js/devsite_devsite_concierge_api_explorer_panel_module.js"});
q.set("devsite-concierge-apix",{src:"/codelabs/js/devsite_devsite_concierge_apix_module.js"});q.set("devsite-concierge-info-panel",{src:"/codelabs/js/devsite_devsite_concierge_info_panel_module.js"});q.set("devsite-concierge-my-activity-panel",{src:"/codelabs/js/devsite_devsite_concierge_my_activity_panel_module.js"});q.set("devsite-concierge-recommendations-panel",{src:"/codelabs/js/devsite_devsite_concierge_recommendations_panel_module.js"});q.set("devsite-content",{src:"/codelabs/js/devsite_devsite_content_module.js"});
q.set("devsite-content-excellence",{src:"/codelabs/js/devsite_devsite_content_excellence_module.js"});q.set("devsite-content-stepper",{src:"/codelabs/js/devsite_devsite_content_stepper_module.js"});q.set("devsite-cookie-notification-bar",{src:"/codelabs/js/devsite_devsite_cookie_notification_bar_module.js"});q.set("devsite-countdown",{src:"/codelabs/js/devsite_devsite_countdown_module.js"});q.set("devsite-credentials-dialog",{src:"/codelabs/js/devsite_devsite_credentials_dialog_module.js"});
q.set("devsite-cse",{src:"/codelabs/js/devsite_devsite_cse_module.js"});q.set("devsite-device",{src:"/codelabs/js/devsite_devsite_device_module.js"});q.set("devsite-devprofile",{src:"/codelabs/js/devsite_devsite_devprofile_module.js"});q.set("devsite-dialog",{src:"/codelabs/js/devsite_devsite_dialog_module.js"});q.set("devsite-dropdown-list",{src:"/codelabs/js/devsite_devsite_dropdown_list_module.js"});q.set("devsite-dynamic-content",{src:"/codelabs/js/devsite_devsite_dynamic_content_module.js"});
q.set("devsite-dynamic-hero",{src:"/codelabs/js/devsite_devsite_dynamic_hero_module.js"});q.set("devsite-edit-profile",{src:"/codelabs/js/devsite_devsite_edit_profile_module.js"});q.set("devsite-engedu-telemetry",{src:"/codelabs/js/devsite_devsite_engedu_telemetry_module.js"});q.set("devsite-expandable",{src:"/codelabs/js/devsite_devsite_expandable_module.js"});q.set("devsite-extradory",{src:"/codelabs/js/devsite_devsite_extradory_module.js"});q.set("devsite-fast-track-profile-creator",{src:"/codelabs/js/devsite_devsite_fast_track_profile_creator_module.js"});
q.set("devsite-feature-tooltip",{src:"/codelabs/js/devsite_devsite_feature_tooltip_module.js"});q.set("devsite-feedback",{src:"/codelabs/js/devsite_devsite_feedback_module.js"});q.set("devsite-filter",{src:"/codelabs/js/devsite_devsite_filter_module.js"});q.set("devsite-filterable-json",{src:"/codelabs/js/devsite_devsite_filterable_json_module.js"});q.set("devsite-footer-linkboxes",{src:"/codelabs/js/devsite_devsite_footer_linkboxes_module.js"});q.set("devsite-footer-promos",{src:"/codelabs/js/devsite_devsite_footer_promos_module.js"});
q.set("devsite-footer-utility",{src:"/codelabs/js/devsite_devsite_footer_utility_module.js"});q.set("devsite-fully-clickable",{src:"/codelabs/js/devsite_devsite_fully_clickable_module.js"});q.set("devsite-googler-buttons",{src:"/codelabs/js/devsite_devsite_googler_buttons_module.js"});q.set("devsite-hats-survey",{src:"/codelabs/js/devsite_devsite_hats_survey_module.js"});q.set("devsite-header",{src:"/codelabs/js/devsite_devsite_header_module.js"});q.set("devsite-heading-link",{src:"/codelabs/js/devsite_devsite_heading_link_module.js"});
q.set("devsite-iframe",{src:"/codelabs/js/devsite_devsite_iframe_module.js"});q.set("devsite-info-popout",{src:"/codelabs/js/devsite_devsite_info_popout_module.js"});q.set("devsite-interests",{src:"/codelabs/js/devsite_devsite_interests_module.js"});q.set("devsite-jsfiddle-button",{src:"/codelabs/js/devsite_devsite_jsfiddle_button_module.js"});q.set("devsite-json-validator",{src:"/codelabs/js/devsite_devsite_json_validator_module.js"});q.set("devsite-jump-to",{src:"/codelabs/js/devsite_devsite_jump_to_module.js"});
q.set("devsite-key-takeaways",{src:"/codelabs/js/devsite_devsite_key_takeaways_module.js"});q.set("devsite-language-selector",{src:"/codelabs/js/devsite_devsite_language_selector_module.js"});q.set("devsite-lightbox",{src:"/codelabs/js/devsite_devsite_lightbox_module.js"});q.set("devsite-mathjax",{src:"/codelabs/js/devsite_devsite_mathjax_module.js"});q.set("devsite-multiple-choice",{src:"/codelabs/js/devsite_devsite_multiple_choice_module.js"});q.set("devsite-mwc",{src:"/codelabs/js/devsite_devsite_mwc_module.js"});
q.set("devsite-my-activity-light",{src:"/codelabs/js/devsite_devsite_my_activity_light_module.js"});q.set("devsite-my-community",{src:"/codelabs/js/devsite_devsite_my_community_module.js"});q.set("devsite-nav-buttons",{src:"/codelabs/js/devsite_devsite_nav_buttons_module.js"});q.set("devsite-notification",{src:"/codelabs/js/devsite_devsite_notification_module.js"});q.set("devsite-openid-user",{src:"/codelabs/js/devsite_devsite_openid_user_module.js"});q.set("devsite-pagination",{src:"/codelabs/js/devsite_devsite_pagination_module.js"});
q.set("devsite-panel",{src:"/codelabs/js/devsite_devsite_panel_module.js"});q.set("devsite-payments-buyflow",{src:"/codelabs/js/devsite_devsite_payments_buyflow_module.js"});q.set("devsite-playlist",{src:"/codelabs/js/devsite_devsite_playlist_module.js"});q.set("devsite-playlist-earnable-badges",{src:"/codelabs/js/devsite_devsite_playlist_earnable_badges_module.js"});q.set("devsite-playlist-summary",{src:"/codelabs/js/devsite_devsite_playlist_summary_module.js"});q.set("devsite-pricing-plans",{src:"/codelabs/js/devsite_devsite_pricing_plans_module.js"});
q.set("devsite-product-catalog",{src:"/codelabs/js/devsite_devsite_product_catalog_module.js"});q.set("devsite-profile-card",{src:"/codelabs/js/devsite_devsite_profile_card_module.js"});q.set("devsite-profile-interests",{src:"/codelabs/js/devsite_devsite_profile_interests_module.js"});q.set("devsite-profile-subscription",{src:"/codelabs/js/devsite_devsite_profile_subscription_module.js"});q.set("devsite-profile-subscription-status",{src:"/codelabs/js/devsite_devsite_profile_subscription_status_module.js"});
q.set("devsite-progress",{src:"/codelabs/js/devsite_devsite_progress_module.js"});q.set("devsite-quiz",{src:"/codelabs/js/devsite_devsite_quiz_module.js"});q.set("devsite-recommendations",{src:"/codelabs/js/devsite_devsite_recommendations_module.js"});q.set("devsite-recommendations-dropdown",{src:"/codelabs/js/devsite_devsite_recommendations_dropdown_module.js"});q.set("devsite-recommendations-sidebar",{src:"/codelabs/js/devsite_devsite_recommendations_sidebar_module.js"});
q.set("devsite-recommended-content",{src:"/codelabs/js/devsite_devsite_recommended_content_module.js"});q.set("devsite-reference-results",{src:"/codelabs/js/devsite_devsite_reference_results_module.js"});q.set("devsite-related-entities",{src:"/codelabs/js/devsite_devsite_related_entities_module.js"});q.set("devsite-rich-tooltip",{src:"/codelabs/js/devsite_devsite_rich_tooltip_module.js"});q.set("devsite-search",{src:"/codelabs/js/devsite_devsite_search_module.js"});
q.set("devsite-search-summary",{src:"/codelabs/js/devsite_devsite_search_summary_module.js"});q.set("devsite-select",{src:"/codelabs/js/devsite_devsite_select_module.js"});q.set("devsite-selector",{src:"/codelabs/js/devsite_devsite_selector_module.js"});q.set("devsite-shell",{src:"/codelabs/js/devsite_devsite_shell_module.js"});q.set("devsite-shell-activate-button",{src:"/codelabs/js/devsite_devsite_shell_activate_button_module.js"});q.set("devsite-sign-in",{src:"/codelabs/js/devsite_devsite_sign_in_module.js"});
q.set("devsite-sitemask",{src:"/codelabs/js/devsite_devsite_sitemask_module.js"});q.set("devsite-snackbar",{src:"/codelabs/js/devsite_devsite_snackbar_module.js"});q.set("devsite-sort",{src:"/codelabs/js/devsite_devsite_sort_module.js"});q.set("devsite-spinner",{src:"/codelabs/js/devsite_devsite_spinner_module.js"});q.set("devsite-sticky-nav",{src:"/codelabs/js/devsite_devsite_sticky_nav_module.js"});q.set("devsite-stripe-checkout",{src:"/codelabs/js/devsite_devsite_stripe_checkout_module.js"});
q.set("devsite-support-form",{src:"/codelabs/js/devsite_devsite_support_form_module.js"});q.set("devsite-switch-to-english-button",{src:"/codelabs/js/devsite_devsite_switch_to_english_button_module.js"});q.set("devsite-tabs",{src:"/codelabs/js/devsite_devsite_tabs_module.js"});q.set("devsite-thumb-rating",{src:"/codelabs/js/devsite_devsite_thumb_rating_module.js"});q.set("devsite-toc",{src:"/codelabs/js/devsite_devsite_toc_module.js"});q.set("devsite-tooltip",{src:"/codelabs/js/devsite_devsite_tooltip_module.js"});
q.set("devsite-topic",{src:"/codelabs/js/devsite_devsite_topic_module.js"});q.set("devsite-tracking-question",{src:"/codelabs/js/devsite_devsite_tracking_question_module.js"});q.set("devsite-user",{src:"/codelabs/js/devsite_devsite_user_module.js"});q.set("devsite-var",{src:"/codelabs/js/devsite_devsite_var_module.js"});q.set("devsite-version-selector",{src:"/codelabs/js/devsite_devsite_version_selector_module.js"});q.set("devsite-video",{src:"/codelabs/js/devsite_devsite_video_module.js"});
q.set("devsite-view-release-notes",{src:"/codelabs/js/devsite_devsite_view_release_notes_module.js"});q.set("devsite-view-release-notes-dialog",{src:"/codelabs/js/devsite_devsite_view_release_notes_dialog_module.js"});q.set("devsite-visibility-analytics",{src:"/codelabs/js/devsite_devsite_visibility_analytics_module.js"});q.set("devsite-vplus",{src:"/codelabs/js/devsite_devsite_vplus_module.js"});q.set("devsite-wall-acknowledgement",{src:"/codelabs/js/devsite_devsite_wall_acknowledgement_module.js"});
q.set("devsite-youtube",{src:"/codelabs/js/devsite_devsite_youtube_module.js"});q.set("goog-split-pane",{src:"/codelabs/js/devsite_goog_split_pane_module.js"});q.set("google-codelab",{src:"/codelabs/js/devsite_google_codelab_module.js"});q.set("google-codelab-about",{src:"/codelabs/js/devsite_google_codelab_about_module.js"});q.set("google-codelab-analytics",{src:"/codelabs/js/devsite_google_codelab_analytics_module.js"});q.set("google-codelab-step",{src:"/codelabs/js/devsite_google_codelab_step_module.js"});
q.set("google-codelab-survey",{src:"/codelabs/js/devsite_google_codelab_survey_module.js"});p("DevsiteAppAuthorizedElements",q);p("DevsiteAppTenantCustomized",!0);function ca(a){n.setTimeout(()=>{throw a;},0)};let u=void 0;function v(a,b){if(a!=null){var c;var e=(c=u)!=null?c:u={};c=e[a]||0;c>=b||(e[a]=c+1,a=Error(),a.__closure__error__context__984382||(a.__closure__error__context__984382={}),a.__closure__error__context__984382.severity="incident",ca(a))}};var w=typeof Symbol==="function"&&typeof Symbol()==="symbol";function x(a,b,c=!1){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?c&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var da=x("jas",void 0,!0),ea=x(void 0,"0actk"),y=x("m_m","tc",!0),fa=x(void 0,"mrtk");const ha={A:{value:0,configurable:!0,writable:!0,enumerable:!1}},ia=Object.defineProperties,z=w?da:"A";var ja;const la=[];A(la,55);ja=Object.freeze(la);function A(a,b){w||z in a||ia(a,ha);a[z]=b};const ma=typeof y==="symbol";var na={};function oa(a){return a!==null&&typeof a==="object"&&!Array.isArray(a)&&a.constructor===Object}var B=Object.freeze({});var E=typeof n.BigInt==="function"&&typeof n.BigInt(0)==="bigint";const pa=Number.MIN_SAFE_INTEGER.toString(),qa=E?BigInt(Number.MIN_SAFE_INTEGER):void 0,ra=Number.MAX_SAFE_INTEGER.toString(),sa=E?BigInt(Number.MAX_SAFE_INTEGER):void 0;function ta(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(let c=0;c<a.length;c++){const e=a[c],f=b[c];if(e>f)return!1;if(e<f)return!0}};const ua=Number.isFinite;function va(a){return a==null?a:ua(a)?a|0:void 0}function F(a){return a==null||typeof a==="string"?a:void 0};function wa(a){return a};function xa(a,b,c){var e=ya;c=c?!!(b&32):void 0;const f=[];let h=a.length,g,k,l,C=!1;if(b&64){if(b&256?(h--,g=a[h],k=h):(k=4294967295,g=void 0),!(b&512)){C=!0;var r;l=((r=za)!=null?r:wa)(g?k- -1:b>>15&1023||536870912,-1,a,g);k=l+-1}}else k=4294967295,b&1||(g=h&&a[h-1],oa(g)?(h--,k=h,l=0):g=void 0);b=void 0;for(r=0;r<h;r++){let t=a[r];if(t!=null&&(t=e(t,c))!=null)if(r>=k){var D=void 0;((D=b)!=null?D:b={})[r- -1]=t}else f[r]=t}if(g)for(let t in g)if(a=g[t],a!=null&&(a=e(a,c))!=null)if(D=+t,D<l)f[D+
-1]=a;else{let ka;((ka=b)!=null?ka:b={})[t]=a}b&&(C?f.push(b):f[k]=b);return f}function ya(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return(E?a>=qa&&a<=sa:a[0]==="-"?ta(a,pa):ta(a,ra))?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[z]|0;return a.length===0&&b&1?void 0:xa(a,b,!1)}b=a[y];const c=b===na;ma&&b&&!c&&v(fa,3);if(c)return G(a);return}return a}let za;function G(a){a=a.g;return xa(a,a[z]|0)};function Aa(){v(ea,5)};var H=function(a,b){a=a.g;return Ba(a,a[z]|0,b)},Ba=function(a,b,c){if(c===-1)return null;const e=c+(b&512?0:-1),f=a.length-1;if(e>=f&&b&256)a=a[f][c];else if(e<=f)a=a[e];else return;return a};function I(a,b,c,e){const f=b&512?0:-1,h=c+f;var g=a.length-1;if(h>=g&&b&256)return a[g][c]=e,b;if(h<=g)return a[h]=e,b;e!==void 0&&(g=b>>15&1023||536870912,c>=g?e!=null&&(a[g+f]={[c]:e},b|=256,A(a,b)):a[h]=e);return b}
function J(a,b,c,e){a=a.g;let f=a[z]|0;const h=2&f?1:e;e=Ba(a,f,b);e=Array.isArray(e)?e:ja;let g=e[z]|0;var k=4&g?!1:!0;if(k){4&g&&(e=Array.prototype.slice.call(e),g=K(g,f),f=I(a,f,b,e));let l=k=0;for(;k<e.length;k++){const C=c(e[k]);C!=null&&(e[l++]=C)}l<k&&(e.length=l);c=g;c===0&&(c=K(c,f),c|=16);g=c|21;g&=-6145;A(e,g);2&g&&Object.freeze(e)}h===1||h===4&&32&g?L(g)||(b=g,g|=2,g!==b&&A(e,g),Object.freeze(e)):(h===2&&L(g)&&(e=Array.prototype.slice.call(e),c=g=K(g,f),g=c&=-33,A(e,g),f=I(a,f,b,e)),L(g)||
(a=b=g,g=a&=-33,g!==b&&A(e,g)));return e}function L(a){return!!(2&a)&&!!(4&a)||!!(1024&a)}function Ca(a){a=a.g;let b=a[z]|0;if(b&2)throw Error();I(a,b,2,"en")}function K(a,b){2&a&&(a|=16);a=(2&b?a|2:a&-3)|32;return a&=-1025}var Da=function(a,b){a=H(a,b);a=a==null||typeof a==="boolean"?a:typeof a==="number"?!!a:void 0;return a!=null?a:!1},M=function(a,b){let c;return(c=F(H(a,b)))!=null?c:""};var N=class{constructor(a){a:{if(a==null){var b=96;a=[]}else{if(!Array.isArray(a))throw Error("narr");b=a[z]|0;8192&b||!(64&b)||2&b||Aa();if(b&1024)throw Error("farr");if(b&64){b&16384||A(a,b|16384);var c=a;break a}var e=a;b|=64;var f=e.length;if(f){var h=f-1;f=e[h];if(oa(f)){b|=256;const g=b&512?0:-1;h-=g;if(h>=1024)throw Error("pvtlmt");for(c in f){const k=+c;k<h&&(e[k+g]=f[c],delete f[c])}b=b&-33521665|(h&1023)<<15}}}A(a,b|16384);c=a}this.g=c}toJSON(){return G(this)}};N.prototype[y]=na;
N.prototype.toString=function(){return this.g.toString()};var Ea={sc:0,rc:1,Rb:6,Pb:8,Xb:12,Zb:14,bc:17,fc:18,ic:21,lc:25,qa:37,mc:38,eb:45,V:47,B:50,N:52,J:62,Na:63,Jb:66,Ab:70,C:73,ob:74,Y:75,Gb:76,Ja:77,La:80,K:81,Za:82,Fa:83,xb:85,fa:87,Aa:89,Cb:90,Ba:91,Ka:92,T:93,pc:94,Ea:95,S:96,Kb:97,D:98,H:99,kc:100,xa:101,Ga:102,Fb:103,oc:104,ka:105,U:106,va:107,oa:108,tb:109,ha:110,nc:112,Hb:113,pa:114,ra:116,bb:117,Ya:118,Ca:119,Bb:120,Vb:121,Ib:122,dc:123,Qb:124,Ua:125,pb:126,wa:127,Wb:128,kb:129,lb:130,ta:131,Sa:132,G:133,Oa:134,ya:135,cb:136,I:137,qc:138,
rb:139,Tb:140,Ob:141,jb:142,Wa:143,P:145,nb:146,Pa:147,Va:148,Db:149,ea:151,Qa:152,hc:156,ec:157,Ma:158,sa:159,L:160,Z:161,la:162,Ub:163,Eb:164,ca:166,Lb:167,da:168,Ta:169,Ra:170,Da:171,mb:174,ub:175,vb:176,qb:177,wb:178,Sb:179,cc:180,aa:181,ja:182,R:183,zb:185,Ha:186,ab:187,ba:188,ia:189,M:191,O:192,Xa:193,Mb:194,za:195,sb:196,ua:197,Nb:198,ib:203,Ia:206,X:207,gb:208,hb:209,W:210,fb:211,ma:212,na:213,Yb:214,yb:215,ac:216,jc:217,F:218};var Fa=class extends N{getTenantId(){var a=va(H(this,1));return a!=null?a:0}getLocale(){return M(this,2)}getInsecureHost(){return M(this,7)}},Ga=function(a){return b=>{if(b==null||b=="")b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error("dnarr");w||z in b||ia(b,ha);b[z]|=32;b=new a(b)}return b}}(Fa);/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
let Ha=globalThis.trustedTypes,O;function Ia(){let a=null;if(!Ha)return a;try{const b=c=>c;a=Ha.createPolicy("goog#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(b){}return a};var Ja=class{constructor(a){this.g=a}toString(){return this.g+""}};function Ka(a=document){let b;const c=(b=a.querySelector)==null?void 0:b.call(a,"script[nonce]");return c==null?"":c.nonce||c.getAttribute("nonce")||""};var La=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),Ma=function(a,b){if(a){a=a.split("&");for(let c=0;c<a.length;c++){const e=a[c].indexOf("=");let f,h=null;e>=0?(f=a[c].substring(0,e),h=a[c].substring(e+1)):f=a[c];b(f,h?decodeURIComponent(h.replace(/\+/g," ")):"")}}};var P=function(a){this.h=this.s=this.j="";this.u=null;this.o=this.g="";this.m=!1;let b;a instanceof P?(this.m=a.m,Q(this,a.j),this.s=a.s,this.h=a.h,R(this,a.u),this.g=a.g,S(this,Na(a.i)),this.o=a.o):a&&(b=String(a).match(La))?(this.m=!1,Q(this,b[1]||"",!0),this.s=T(b[2]||""),this.h=T(b[3]||"",!0),R(this,b[4]),this.g=T(b[5]||"",!0),S(this,b[6]||"",!0),this.o=T(b[7]||"")):(this.m=!1,this.i=new U(null,this.m))};
P.prototype.toString=function(){const a=[];var b=this.j;b&&a.push(V(b,Oa,!0),":");var c=this.h;if(c||b=="file")a.push("//"),(b=this.s)&&a.push(V(b,Oa,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.u,c!=null&&a.push(":",String(c));if(c=this.g)this.h&&c.charAt(0)!="/"&&a.push("/"),a.push(V(c,c.charAt(0)=="/"?Pa:Qa,!0));(c=this.i.toString())&&a.push("?",c);(c=this.o)&&a.push("#",V(c,Ra));return a.join("")};
P.prototype.resolve=function(a){const b=new P(this);let c=!!a.j;c?Q(b,a.j):c=!!a.s;c?b.s=a.s:c=!!a.h;c?b.h=a.h:c=a.u!=null;var e=a.g;if(c)R(b,a.u);else if(c=!!a.g){if(e.charAt(0)!="/")if(this.h&&!this.g)e="/"+e;else{var f=b.g.lastIndexOf("/");f!=-1&&(e=b.g.slice(0,f+1)+e)}f=e;if(f==".."||f==".")e="";else if(f.indexOf("./")!=-1||f.indexOf("/.")!=-1){e=f.lastIndexOf("/",0)==0;f=f.split("/");const h=[];for(let g=0;g<f.length;){const k=f[g++];k=="."?e&&g==f.length&&h.push(""):k==".."?((h.length>1||h.length==
1&&h[0]!="")&&h.pop(),e&&g==f.length&&h.push("")):(h.push(k),e=!0)}e=h.join("/")}else e=f}c?b.g=e:c=a.i.toString()!=="";c?S(b,Na(a.i)):c=!!a.o;c&&(b.o=a.o);return b};
var Q=function(a,b,c){a.j=c?T(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))},R=function(a,b){if(b){b=Number(b);if(isNaN(b)||b<0)throw Error("Bad port number "+b);a.u=b}else a.u=null},S=function(a,b,c){b instanceof U?(a.i=b,Sa(a.i,a.m)):(c||(b=V(b,Ta)),a.i=new U(b,a.m))},Ua=function(a){return a instanceof P?new P(a):new P(a)},T=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},V=function(a,b,c){return typeof a==="string"?(a=encodeURI(a).replace(b,Va),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,
"%$1")),a):null},Va=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Oa=/[#\/\?@]/g,Qa=/[#\?:]/g,Pa=/[#\?]/g,Ta=/[#\?@]/g,Ra=/#/g,U=function(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b},W=function(a){a.g||(a.g=new Map,a.h=0,a.i&&Ma(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};U.prototype.add=function(a,b){W(this);this.i=null;a=X(this,a);let c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h+=1;return this};
U.prototype.remove=function(a){W(this);a=X(this,a);return this.g.has(a)?(this.i=null,this.h-=this.g.get(a).length,this.g.delete(a)):!1};U.prototype.clear=function(){this.g=this.i=null;this.h=0};var Wa=function(a,b){W(a);b=X(a,b);return a.g.has(b)};U.prototype.forEach=function(a,b){W(this);this.g.forEach(function(c,e){c.forEach(function(f){a.call(b,f,e,this)},this)},this)};
var Xa=function(a,b){W(a);let c=[];if(typeof b==="string")Wa(a,b)&&(c=c.concat(a.g.get(X(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};U.prototype.set=function(a,b){W(this);this.i=null;a=X(this,a);Wa(this,a)&&(this.h-=this.g.get(a).length);this.g.set(a,[b]);this.h+=1;return this};U.prototype.get=function(a,b){if(!a)return b;a=Xa(this,a);return a.length>0?String(a[0]):b};
U.prototype.toString=function(){if(this.i)return this.i;if(!this.g)return"";const a=[],b=Array.from(this.g.keys());for(let e=0;e<b.length;e++){var c=b[e];const f=encodeURIComponent(String(c));c=Xa(this,c);for(let h=0;h<c.length;h++){let g=f;c[h]!==""&&(g+="="+encodeURIComponent(String(c[h])));a.push(g)}}return this.i=a.join("&")};
var Na=function(a){const b=new U;b.i=a.i;a.g&&(b.g=new Map(a.g),b.h=a.h);return b},X=function(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b},Sa=function(a,b){b&&!a.j&&(W(a),a.i=null,a.g.forEach(function(c,e){var f=e.toLowerCase();if(e!=f&&(this.remove(e),this.remove(f),c.length>0)){this.i=null;e=this.g;var h=e.set;f=X(this,f);var g=c.length;if(g>0){const k=Array(g);for(let l=0;l<g;l++)k[l]=c[l];g=k}else g=[];h.call(e,f,g);this.h+=c.length}},a));a.j=b};const Ya={};function Za(a,b){var c=Ya[a];if(c!==void 0&&(!c.v||Date.now()<=c.v+3E5))return c.p;c=new Promise((f,h)=>{b.onload=()=>f(b);b.onerror=g=>{b.parentNode&&b.parentNode.removeChild(b);h(g)};document.head.appendChild(b)});const e={v:0,p:c};c.catch(()=>e.v=+new Date);Ya[a]=e;return c}
var $a=function(a){a=Ua(a);const b=document.createElement("script");var c=a.toString();c=c===null?"null":c===void 0?"undefined":c;O===void 0&&(O=Ia());var e=O;c=new Ja(e?e.createScriptURL(c):c);if(c instanceof Ja)c=c.g;else throw Error("");b.src=c;(c=Ka(b.ownerDocument))&&b.setAttribute("nonce",c);return Za(a.toString(),b)};class ab{constructor(){this.promise=new Promise((a,b)=>{this.resolve=a;this.reject=b})}};var Y=function(a="Devsite has failed to load."){document.documentElement.removeAttribute("cached");console.error(a)},cb=async function(){var a=Z;const b=new ab;p("__devsiteAppReadyResolver",b.resolve);p("__devsiteAppReadyPromise",b.promise);p("DevsiteApp.whenReady",()=>b.promise);if(J(a.config,12,F,void 0===B?2:4).length)try{await Promise.all(J(a.config,12,F,void 0===B?2:4).map(f=>{f=Ua(f);const h=document.createElement("link");h.setAttribute("rel","stylesheet");h.setAttribute("type","text/css");
h.setAttribute("href",f.toString());return Za(f.toString(),h)}))}catch(f){Y(`Failed to load Devsite App dependencies: ${f.message}`);return}const c=n.DevsiteAppTenantCustomized?M(a.config,6):M(a.config,5);try{await $a(`${c}${bb(a)}`)}catch(f){if(a.config.getLocale()!=="en"){Ca(a.config);try{await $a(`${c}${M(a.config,4)}`)}catch(h){Y(`Failed to load Devsite App binary: ${h.message}`);return}}else{Y(`Failed to load Devsite App binary: ${f.message}`);return}}const e=document;if(e.readyState!=="complete"&&
e.readyState!=="interactive"){const f=new ab;e.addEventListener("readystatechange",()=>{e.readyState!=="interactive"&&e.readyState!=="complete"||f.resolve()});await f.promise}},bb=function(a){const b=a.config.getLocale();a=M(a.config,4);return b&&b!=="en"?a.replace(/\.js$/,`__${b.toLowerCase().replace("-","_")}.js`):a};
const Z=new class{constructor(){this.g=null;this.config=new Fa;this.h=[];this.i=a=>{this.h.push(a)};this.m=()=>{this.j()};if(n.__globalAppLoader)return n.__globalAppLoader;try{this.config=Ga(`${GoogleDevelopersObject}`.replaceAll("\n",""))}catch(a){Y("GoogleDevelopersObject missing or invalid");return}GoogleDevelopersObject=null;p("__globalAppLoader",this);p("DevsiteApp.hasFlagAccess",a=>this.hasFlagAccess(a));p("DevsiteApp.hasMendelFlagAccess",(a,b)=>this.hasMendelFlagAccess(a,b))}j(){var a=document.querySelector("devsite-content");
a&&(window.removeEventListener("message",this.i),a.removeEventListener("devsite-content-updated",this.m));a=window;for(const b of this.h)a.dispatchEvent(b);this.h=[]}getEnv(){if(Da(this.config,11))return"PROD";const a=document.location.hostname;return a.endsWith("test.devsite.corp.google.com")||a.endsWith("test.devsite-v2-staging.googleplex.com")?"TEST":a.endsWith(".devsite.corp.google.com")||a.endsWith("devsite-v2-staging.googleplex.com")?"STAGE":"DEV"}hasFlagAccess(a){var b=this.getEnv();var c=
J(this.config,13,va,B===B?2:4);a:{var e=new URL(document.location.toString());e=new P(e.href);const f=Object.keys(Ea);if(b!=="PROD")for(const h of f)if(Ea[h]===a&&(b=e.i.get(h),b!==void 0)){a=b==="true";break a}a=Array.from(c).includes(a)}return a}hasMendelFlagAccess(a,b){var c=this.getEnv();var e=J(this.config,22,F,B===B?2:4);a:{var f=new URL(document.location.toString());f=new P(f.href);a=a+"__"+b;if(c!=="PROD"&&(c=f.i.get(a),c!==void 0)){e=c==="true";break a}e=Array.from(e).includes(a)}return e}},
db=document.querySelector("devsite-content");db&&(window.addEventListener("message",Z.i),db.addEventListener("devsite-content-updated",Z.j.bind(Z)));
(async function(){const a=window;if("WeakMap"in a&&"performance"in a&&"now"in a.performance)return Z.g||(Z.g=cb()),Z.g})().then(()=>{Da(Z.config,9)?n.DevsiteAppFrameboxInit?DevsiteAppFrameboxInit(JSON.stringify(G(Z.config)),n.DevsiteAppAuthorizedElements):Y("Failed to load Devsite App binary"):n.DevsiteAppInit?DevsiteAppInit(JSON.stringify(G(Z.config)),n.DevsiteAppAuthorizedElements):Y("Failed to load Devsite App binary")});}).call(this);
