(function(_ds){var window=this;var H$=function(a,b,c,d,e){_ds.XT.call(this);this.h=a;this.oa=b;this.ra=c;this.j=d;this.ea=Array.isArray(e)?e:[e]},I$=async function(a){let b=void 0;var c=new _ds.JQ;try{var d;b=(d=await _ds.yQ(c,new _ds.NN))==null?void 0:d.Fa()}catch(e){}if(!b||!b.Ca())return!1;c=_ds.A().href;try{c=await _ds.Su(c)}catch(e){return!1}d=new _ds.mQ;try{return await d.oe({path:c,status:a,profileId:`${b.Ca()}`}),!0}catch(e){}return!1},Lva=async function(a){let b=void 0;var c=new _ds.JQ;try{var d;b=(d=await _ds.yQ(c,new _ds.NN))==
null?void 0:d.Fa()}catch(e){}if(!b||!b.Ca())return!1;c=_ds.A().href;try{c=await _ds.Su(c)}catch(e){}d=new _ds.mQ;try{return await d.Mf({path:c,profileId:`${b.Ca()}`,voucher:a}),!0}catch(e){}return!1},Mva=class{async Dj(){I$("STARTED")}async Cj(){return I$("COMPLETED")}async Au(a){return Lva(a)}};var J$=async function(a,b){if(a){const c=await _ds.u(),d=await c.getStorage().get(b,"");let e={};if(d)try{e=JSON.parse(d)}catch(f){console.warn("Could not deserialize codelab status from local storage"+` at path ${b}. Will start with an empty state.`)}e[a]=!0;await c.getStorage().set("devsite-codelabs",b,JSON.stringify(e));return!0}return!1},Nva=class{async Dj(a){await J$(a,"started_codelabs")}async Cj(a){return await J$(a,"completed_codelabs")}async Au(){return!0}};var Ova=function(a){var b=a.Yx;const c=a.Xx;a='<div class="devsite-banner codelab-banner"><div class="devsite-banner-message medium"><a href="'+_ds.V(_ds.MA(b))+'"><i class="material-icons">chevron_left</i><span>';c?(b="Back to "+_ds.T(c),a+=b):(b="Back to "+_ds.T(b),a+=b);return(0,_ds.Q)(a+"</span></a></div></div>")},Pva=function(a){const b=a.result,c=a.total,d=a.Vb;return(0,_ds.Q)("<android-codelab-grader voucherCode="+_ds.BA(a.Bm)+' result="'+_ds.V(b)+'" total="'+_ds.V(c)+'"'+(d?' return-uri="'+
_ds.V(_ds.MA(d))+'"':"")+"></android-codelab-grader>")};var Qva=function(a,b){Array.isArray(b)||(b=[b]);b=b.map(function(c){return typeof c==="string"?c:c.dB+" "+c.duration+"s "+c.timing+" "+c.delay+"s"});K$(a,b.join(","))},Rva=function(a){let b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=_ds.zl(document,"DIV"),b=_ds.Rh?"-webkit":_ds.Qh?"-moz":null;let c="transition:opacity 1s linear;";b&&(c+=b+"-transition:opacity 1s linear;");_ds.Of(a,_ds.fg("div",{style:c}));a=a.firstChild;b=a.style[_ds.ll("transition")];return(typeof b!=="undefined"?
b:a.style[_ds.Jo(a,"transition")]||"")!=""}),K$=function(a,b){_ds.Ko(a,"transition",b)};_ds.xh(H$,_ds.XT);_ds.p=H$.prototype;_ds.p.Dh=function(){this.isPlaying()||(this.wl(),this.Lc("play"),this.startTime=_ds.vh(),this.g=1,Rva()?(_ds.Ko(this.h,this.ra),this.o=_ds.Eo(this.KA,void 0,this)):this.Xq(!1))};_ds.p.KA=function(){_ds.Vo(this.h);Qva(this.h,this.ea);_ds.Ko(this.h,this.j);this.o=_ds.Eo((0,_ds.Ug)(this.Xq,this,!1),this.oa*1E3)};_ds.p.stop=function(){this.isPlaying()&&this.Xq(!0)};
_ds.p.Xq=function(a){K$(this.h,"");_ds.ja.clearTimeout(this.o);_ds.Ko(this.h,this.j);this.endTime=_ds.vh();this.g=0;a?this.Lc("stop"):this.Lc("finish");this.aj()};_ds.p.Va=function(){this.stop();H$.pb.Va.call(this)};var Sva=function(a){const b=a.hc;a=a.Cz;let c='<div id="codelab-title"><div id="codelab-nav-buttons"><a href="'+_ds.V(_ds.MA(a))+'" id="arrow-back"><i class="material-icons">close</i></a><a href="#" id="menu"><i class="material-icons">menu</i></a></div><div class="codelab-time-container"></div></div><nav id="drawer"></nav><div id="main"><div id="steps"></div><div id="controls"><div id="fabs"><a href="#" id="previous-step" title="';c+=_ds.xA("Previous step");c=c+'">Back</a><div class="spacer"></div><a href="#" id="next-step" title="'+
_ds.xA("Next step");c=c+'">Next</a><a href="'+(_ds.V(_ds.MA(a))+'" id="done" hidden title="');c+=_ds.xA("Codelab complete");c+='">Done</a></div></div></div><div class="metadata"><a';b?(c=c+' target="_blank" aria-label="'+_ds.xA(" Report a mistake (opens in a new tab)"),c+='" href="'+_ds.V(_ds.MA(b))+'"'):c+=' href="#" id="codelab-feedback"';return(0,_ds.Q)(c+'><i class="material-icons">bug_report</i> Report a mistake</a></div>')},Tva=function(a){const b=a.title;return(0,_ds.Q)('<h1 is-upgraded class="title"><a href="'+
_ds.V(_ds.MA(a.url))+'">'+_ds.T(b)+"</a></h1>")},Uva=function(a){var b=a.time;a='<div class="time-remaining" tabindex="0" role="timer" title="';if(b===1){var c="Estimated time remaining: "+_ds.V(b)+" minute";a+=_ds.xA(c)}else c="Estimated time remaining: "+_ds.V(b)+" minutes",a+=_ds.xA(c);a+='"><i class="material-icons">access_time</i>';b===1?(b=_ds.T(b)+" min remaining",a+=b):(b=_ds.T(b)+" mins remaining",a+=b);return(0,_ds.Q)(a+"</div>")},Vva=function(a){let b='<div class="codelab-time-container"></div><div class="steps"><ol>';
a=a.steps;const c=a.length;for(let d=0;d<c;d++){const e=a[d];b+='<li><a href="#'+_ds.V(d)+'"><span class="step"><span>'+_ds.T(e)+"</span></span></a></li>"}return(0,_ds.Q)(b+"</ol></div>")};/*

 Copyright 2018 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var L$=function(a){a.hash=`#${a.g}`;a.qa&&a.ec.set(`progress_${a.qa}`,String(a.g))},M$=function(a,b,c={}){b=new CustomEvent(b,{detail:c,bubbles:!0});a.dispatchEvent(b)},N$=function(a){if(a.ea&&a.o){var b=new URL(document.location.href);b.hash="";b=_ds.J(Tva,{title:a.ea,url:b.href});document.title=a.ea;var c=a.o.querySelector("h1");a=a.o.querySelector("#codelab-nav-buttons");c?_ds.Fl(b,c):a.parentNode&&a.parentNode.insertBefore(b,a.nextSibling)}},P$=function(a){a.removeAttribute("drawer--open");let b=
0;if(a.hasAttribute("selected")){if(b=parseInt(a.getAttribute("selected"),10),b=Math.min(Math.max(0,b),a.steps.length-1),a.g!==b&&!isNaN(b)){var c=a.steps[b];if(a.g===-1)c.setAttribute("selected","");else{a.va&&a.va.stop();a.xa&&a.xa.stop();_ds.C(a.Wa);const d={},e={},f=a.steps[a.g];c.setAttribute("animating","");a.g<b?(d.transform="translate3d(110%, 0, 0)",e.transform="translate3d(-110%, 0, 0)"):(d.transform="translate3d(-110%, 0, 0)",e.transform="translate3d(110%, 0, 0)");const g=[{dB:"transform",
duration:.5,delay:0,timing:"cubic-bezier(0.4, 0, 0.2, 1)"}];a.va=new H$(c,.5,d,{transform:"translate3d(0, 0, 0)"},g);a.xa=new H$(f,.5,{transform:"translate3d(0, 0, 0)"},e,g);a.va.Dh();a.xa.Dh();_ds.Ho(a.Wa,a.va,["finish","stop"],()=>{c.setAttribute("selected","");c.removeAttribute("animating")});_ds.Ho(a.Wa,a.xa,["finish","stop"],()=>{f.removeAttribute("selected")})}a.g=b;O$(a);clearTimeout(a.bd);a.bd=setTimeout(()=>{c.focus()},500);a.ua&&a.v&&a.Da&&(b===0?(a.v.setAttribute("aria-hidden",""),a.v.setAttribute("disappear",
""),a.v.setAttribute("tabindex","-1")):(a.v.removeAttribute("aria-hidden"),a.v.removeAttribute("disappear"),a.v.removeAttribute("tabindex")),b===a.steps.length-1?(a.ua.setAttribute("hidden",""),a.Da.removeAttribute("hidden"),M$(a,"google-codelab-action",{category:"codelab",action:"complete",label:a.ea})):(a.ua.removeAttribute("hidden"),a.Da.setAttribute("hidden","")));a.h&&a.h.querySelectorAll("li").forEach((d,e)=>{e<=b?d.setAttribute("completed",""):d.removeAttribute("completed");e===b?d.setAttribute("selected",
""):d.removeAttribute("selected")});Wva(a)}}else a.setAttribute("selected",b)},Q$=function(a){a.o&&(a.hasAttribute("no-toolbar")?a.o.setAttribute("hidden",""):a.o.removeAttribute("hidden"))},R$=function(a){a.Ea&&(a.hasAttribute("no-arrows")?a.Ea.setAttribute("hidden",""):a.Ea.removeAttribute("hidden"))},S$=function(a){O$(a);window.requestAnimationFrame(()=>{document.body.removeAttribute("unresolved");M$(a,"google-codelab-action",{category:"codelab",action:"ready"})})},Xva=function(a){const b=document.querySelector("google-codelab-analytics");
if(b){var c=a.getAttribute("codelab-gaid");c&&b.setAttribute("codelab-gaid",c);(c=a.getAttribute("codelab-ga4id"))&&b.setAttribute("codelab-ga4id",c);a.qa&&b.setAttribute("codelab-id",a.qa);b.setAttribute("environment",a.getAttribute("environment"));b.setAttribute("category",a.getAttribute("category"))}},T$=function(a){return a&&(a=parseInt(a.substring(1),10),!isNaN(a)&&a)?a:0},Wva=function(a){if(a.Na&&a.Na.length){var b=0;for(let c=a.g;c<a.steps.length;c++){let d=parseInt(a.steps[c].getAttribute("duration"),
10);d&&(b+=d)}Array.prototype.forEach.call(a.Na,c=>{if(b){var d=_ds.J(Uva,{time:b}),e=c.querySelector(".time-remaining");e?_ds.Fl(d,e):c.appendChild(d)}else c.style.display="none"})}},Yva=function(a){a.steps.forEach((b,c)=>{b.setAttribute("step",c)})},O$=function(a){M$(a,"google-codelab-pageview",{page:location.pathname+"#"+a.g,title:a.steps[a.g].getAttribute("label")})},Zva=function(a){return a.replace(/&amp;#(\d+);/g,function(b,c){return String.fromCharCode(c)})},$va=function(a){const b=a.steps.map(c=>
Zva(c.getAttribute("label")));_ds.G(a.h,Vva,{steps:b})},awa=function(){let a=(new URL(document.location.href)).searchParams.get("index");if(!a)return"/";a=a.replace(/[^a-z0-9\-]+/ig,"");if(!a||a.trim()==="")return"/";a==="index"&&(a="");return(new URL(a,document.location.origin)).pathname},U$=class extends HTMLElement{constructor(){super();this.Da=this.Ea=this.v=this.ua=this.o=this.Na=this.xe=this.h=null;this.ea=this.qa="";this.bd=-1;this.steps=[];this.g=-1;this.j=new _ds.B;this.Wa=new _ds.B;this.Db=
!1;this.xa=this.va=null;this.ec=new _ds.eh}connectedCallback(){this.qa=this.getAttribute("id");var a;(a=T$(this.hash))||(a=parseInt(this.ec.get(`progress_${this.qa}`),10),a=!isNaN(a)&&a?a:0);this.setAttribute("selected",`${a}`);this.Ka();this.Ia();L$(this);this.Db||(this.Db=!0,M$(this,"google-codelab-ready"),this.setAttribute("google-codelab-ready",""))}disconnectedCallback(){_ds.C(this.j);_ds.C(this.Wa)}static get observedAttributes(){return"title codelab-title environment category feedback-link selected last-updated no-toolbar no-arrows anayltics-ready".split(" ")}attributeChangedCallback(a){switch(a){case "title":this.hasAttribute("title")&&
(this.ea=this.getAttribute("title"),this.removeAttribute("title"),this.setAttribute("codelab-title",this.ea));break;case "codelab-title":this.ea=this.getAttribute("codelab-title");N$(this);break;case "selected":P$(this);L$(this);break;case "no-toolbar":Q$(this);break;case "no-arrows":R$(this);break;case "anayltics-ready":this.hasAttribute("anayltics-ready")&&(this.Db?S$(this):this.j.listen(this,"google-codelab-ready",()=>S$(this)))}}get eventHandler(){return this.j}Hq(){this.setAttribute("selected",
this.g+1)}Iq(){this.setAttribute("selected",this.g-1)}select(a){this.setAttribute("selected",a)}get hash(){return window.location.hash}set hash(a){a!==""&&window.location.hash!==a&&window.history.replaceState({nK:a},document.title,a)}Ia(){this.v&&this.j.listen(this.v,"click",b=>{b.preventDefault();b.stopPropagation();this.Iq()});this.ua&&this.j.listen(this.ua,"click",b=>{b.preventDefault();b.stopPropagation();this.Hq()});this.h&&(this.j.listen(this.h,"click",b=>{let c=b.target;for(;c!==this.h&&c.tagName.toUpperCase()!==
"A";)b.preventDefault(),b.stopPropagation(),c=c.parentNode;c!==this.h&&(b=(new URL(c.getAttribute("href"),document.location.origin)).hash,this.setAttribute("selected",`${T$(b)}`))}),this.j.listen(this.h,"keydown",b=>{if(this.h){var c=this.h.querySelector(":focus"),d;c?d=c.parentNode:d=this.h.querySelector("[selected]");if(d){var e;b.keyCode==38?e=_ds.Jl(d):b.keyCode==40&&(e=_ds.Il(d));e&&(b=e.querySelector("a"))&&b.focus()}}}));if(this.o){var a=this.o.querySelector("#menu");a&&(this.j.listen(a,"click",
b=>{b.preventDefault();b.stopPropagation();this.hasAttribute("drawer--open")?this.removeAttribute("drawer--open"):this.setAttribute("drawer--open","")}),this.j.listen(document.body,"click",()=>{this.hasAttribute("drawer--open")&&this.removeAttribute("drawer--open")}))}this.j.listen(document.body,"keydown",b=>{b.keyCode==37?(document.activeElement&&document.activeElement.blur(),this.Iq()):b.keyCode==39&&(document.activeElement&&document.activeElement.blur(),this.Hq())});(a=this.querySelector("#codelab-feedback"))&&
this.j.listen(a,"click",b=>{"userfeedback"in window&&(window.userfeedback.api.startFeedback({productId:"5143948"}),b.preventDefault())})}Ka(){this.steps=Array.from(this.querySelectorAll("google-codelab-step"));const a=this.getAttribute("feedback-link");_ds.G(this,Sva,{hc:a,Cz:awa()});this.h=this.querySelector("#drawer");this.o=this.querySelector("#codelab-title");this.xe=this.querySelector("#steps");this.Ea=this.querySelector("#controls");this.v=this.querySelector("#controls #previous-step");this.ua=
this.querySelector("#controls #next-step");this.Da=this.querySelector("#controls #done");this.steps.forEach(b=>{this.xe.appendChild(b)});Yva(this);$va(this);this.Na=this.querySelectorAll(".codelab-time-container");Xva(this);P$(this);N$(this);R$(this);Q$(this)}};U$.prototype.select=U$.prototype.select;U$.prototype.selectPrevious=U$.prototype.Iq;U$.prototype.selectNext=U$.prototype.Hq;U$.prototype.attributeChangedCallback=U$.prototype.attributeChangedCallback;U$.prototype.disconnectedCallback=U$.prototype.disconnectedCallback;
U$.prototype.connectedCallback=U$.prototype.connectedCallback;var bwa=async function(a){if(a.g===a.steps.length-1&&a.oa){await a.Lb.Cj(a.oa);let b;(b=window.opener)==null||b.postMessage({url:_ds.A().href,action:"codelab-completed"},"*");a.setAttribute("google-codelab-completed","");M$(a,"google-codelab-completed",{"codelab-id":a.oa})}},dwa=async function(a){let b;var c=((b=_ds.Qm())==null?void 0:b.href)||"";c&&(a=await cwa(a,c),c=_ds.J(Ova,{Yx:c,Xx:a}),(a=document.querySelector(".devsite-article"))&&a.insertBefore(c,a.querySelector(".devsite-article-meta")))},
ewa=async function(a){var b=document.querySelector("devsite-language-selector");if(b){b=b.cloneNode(!0);var c=b.querySelector(".devsite-select");c&&c.remove();c=b.cloneNode(!0);var d=a.querySelector("devsite-user"),e=a.querySelector("#codelab-title");b&&(e==null||e.insertBefore(b,d));a=a.querySelector("#controls .spacer");c&&(a==null||a.appendChild(c))}},fwa=function(a){if(a.ma){a.Nj.observe(a.ma,{childList:!0,subtree:!0,attributes:!0,attributeFilter:["class"]});var b=a.querySelectorAll(".step-title");
b.length>0&&a.Mj.observe(b[b.length-1])}},gwa=function(a){const b=a.querySelector("#codelab-feedback");b&&a.eventHandler.listen(b,"click",c=>{c.preventDefault();let d;_ds.Wt({productId:"5143948",locale:((d=a.app)==null?void 0:d.getLocale())||"en"})})},hwa=async function(a,b){await a.Lb.Au(b)},cwa=async function(a,b){let c;a=await ((c=a.app)==null?void 0:c.fetchPageTitle(b))||"";a=a.replaceAll("&nbsp;"," ");return a.split("|")[0].trim()},iwa=class extends U${constructor(a=null){super();this.Ha="";
this.Ec=!1;this.Nj=new MutationObserver(d=>{if(this.isConnected)for(const g of d)if(d=g.target,d.classList.contains("devsite-nav-active")){let h;const k=(h=this.ma)==null?void 0:h.querySelector("devsite-toc > .devsite-nav-list > .devsite-nav-heading .devsite-nav-text");let l;const m=Array.from(((l=this.ma)==null?void 0:l.querySelectorAll("devsite-toc > .devsite-nav-list > .devsite-nav-item:not(.devsite-nav-heading)"))||[]);for(const [n,q]of m.entries()){var e=n,f=q;f.removeAttribute("completed");
if(f.querySelector(".devsite-nav-active")){f=0;for(let r=0;r<e;r++)f+=this.ra[r],m[r].setAttribute("completed","");e=this.Ma-f;k&&(e=(new _ds.qw("{MINUTES_REMAINING, plural, =1 {1 minute remaining}other {# minutes remaining}}")).format({MINUTES_REMAINING:e}),k.textContent=e)}}d.parentElement&&(d=m.indexOf(d.parentElement),d>0&&this.select(d))}});this.Mj=new IntersectionObserver(d=>{if(this.isConnected){var e,f=(e=this.ma)==null?void 0:e.querySelector(`[href="#${d[0].target.id}"]`);if(d[0].isIntersecting){let g,
h;(h=(g=this.ma)==null?void 0:g.querySelector(".devsite-nav-active"))==null||h.classList.remove("devsite-nav-active");f==null||f.classList.add("devsite-nav-active")}else f==null||f.classList.remove("devsite-nav-active")}});this.ra=[];this.Ma=0;this.Bb=!0;this.layout=this.oa="";this.app=this.ma=null;this.Ra=new _ds.Mg;this.Qh=new _ds.Vg(()=>{this.g>=1&&this.g!==this.steps.length-1&&this.oa&&this.Lb.Dj(this.oa)},500);this.Ph=new _ds.Vg(()=>{bwa(this)},500);this.Lb=a||new Nva;this.Rb=null;a=_ds.A().searchParams;
const b=a.get("pc")||"",c=a.get("tc")||"";this.Ga={result:b,total:c,Bm:a.get("vc")};this.An=b.length>0&&c.length>0}async connectedCallback(){this.Ha=this.hash;this.Ma=0;this.ra=[];this.app=await _ds.u();if(this.Ec=await this.app.hasMendelFlagAccess("MiscFeatureFlags","enable_codelabs_as_a_content_type"))this.layout="scrolling";else switch((this.getAttribute("layout")||"").toLowerCase()){case "paginated":this.layout="paginated";break;case "scrolling":this.layout="scrolling";break;default:this.layout=
"paginated"}document.body.setAttribute("codelabs-content-type",this.layout);this.oa=this.getAttribute("id")||"";this.steps=Array.from(this.querySelectorAll("google-codelab-step"));var a;this.Bb=((a=document.querySelector('meta[name="award_behavior"]'))==null?void 0:a.getAttribute("value"))!=="award-behavior-disable-all";this.ma=document.querySelector("devsite-toc:not([devsite-toc-embedded])");super.connectedCallback();if(a=_ds.Qm())a={virtualPath:`${_ds.an(document.location.pathname)}?continue=${a.href}`},
this.dispatchEvent(new CustomEvent("devsite-analytics-pageview",{detail:a,bubbles:!0}));(a=this.querySelector("google-codelab-about .about-card"))||(a=this.querySelector("google-codelab-about"));if(a){var b=document.querySelectorAll("devsite-content .devsite-banner-translated");for(const c of b)a.appendChild(c)}this.Ra.resolve()}disconnectedCallback(){super.disconnectedCallback();document.body.removeAttribute("codelabs-content-type");let a;(a=this.querySelector("style"))==null||a.remove();this.Nj.disconnect();
this.Mj.disconnect();this.Ra=new _ds.Mg}async attributeChangedCallback(a,b,c,d){await this.Ra.promise;if(this.isConnected)if(this.layout==="scrolling")switch(a){case "selected":a=Number(c),a!==this.g&&(this.g=a,L$(this),O$(this))}else this.layout!=="paginated"&&this.layout!=="paginated"||super.attributeChangedCallback(a,b,c,d)}async Ka(){var a;if(this.layout==="scrolling"){var b=this.querySelectorAll("google-codelab-step");for(var c of b)b=c.getAttribute("duration")||"0",this.ra.push(Number(b));for(c=
0;c<this.ra.length;c++)this.Ma+=this.ra[c];c=document.createElement("style");c.textContent="html{scroll-behavior:smooth}";this.appendChild(c);await dwa(this);this.Ha!==""&&this.Ha!=="#-1"&&(await _ds.Vm(),await ((a=this.app)==null?void 0:a.scrollToAnchor(this.Ha)));a="Scrolling codelab layout"}else if(this.layout==="paginated"||this.layout==="paginated")super.Ka(),a=this.querySelector("#codelab-title"),c=document.createElement("devsite-user"),a==null||a.appendChild(c),a=this.querySelector("#arrow-back"),
c=this.querySelector("#done"),(b=_ds.Qm())?(this.Rb=b.toString(),a&&_ds.Hf(a,this.Rb),c&&_ds.Hf(c,this.Rb)):(a==null||a.classList.add("no-return-url"),c==null||c.classList.add("no-return-url")),await ewa(this),a="Paginated codelab layout";else return;this.ya({category:"Site-Wide Custom Events",action:"Codelab displayed",label:a,nonInteraction:!0});this.Dj();if(this.An){a=this.Ga.result;c=this.Ga.total;b=this.Ga.Bm;var d;const e=((d=_ds.Qm())==null?void 0:d.href)||"";a&&c&&b&&(d=_ds.J(Pva,{result:a,
total:c,Bm:b,Vb:e}),document.body.appendChild(d))}this.Bb&&await this.Cj()}async Ia(){if(this.layout==="scrolling")fwa(this);else if(this.layout==="paginated"||this.layout==="paginated")super.Ia();else return;gwa(this);this.eventHandler.listen(this,"google-codelab-pageview",()=>{this.Dj();this.Bb&&this.Cj()});this.eventHandler.listen(document,"devsite-project-result-shown",()=>{let a;const b=(a=this.Ga)==null?void 0:a.Bm;b&&hwa(this,b)})}async Cj(){this.Ph.Ua()}Dj(){this.Qh.Ua()}ya(a){this.dispatchEvent(_ds.lf(a))}};var V$=async function(a){await (await _ds.u()).hasMendelFlagAccess("Profiles","enable_completecodelab_endpoint")?await a.nf():await Promise.all([jwa(a),kwa()])},jwa=async function(a){if(W$()){var b=a.getAttribute("badge-path");if(b)if(a=new URL(b,"https://developers.google.com"),a.pathname.startsWith("/profile/badges/codelabs/")){b=void 0;if(await (await _ds.u()).isSignedIn()){const f=new _ds.JQ;try{var c;b=(c=await _ds.yQ(f,new _ds.NN))==null?void 0:c.Fa()}catch(g){}}var d,e;c=(e=(d=b)==null?void 0:
d.Ca())!=null?e:void 0;d=new _ds.YP;try{await d.Zb({url:a.href,profileId:c})}catch(f){}}else console.error(`The path of the codelab's badge is incorrect. ${b} must start with "${"/profile/badges/codelabs/"}" and point to a directory containing a "_badge.yaml" file`)}},kwa=async function(){if(W$()){var a=await _ds.u();if(await a.hasMendelFlagAccess("Profiles","enable_recognition_badges")){var b=void 0;if(await a.isSignedIn()){a=new _ds.JQ;try{var c;b=(c=await _ds.yQ(a,new _ds.NN))==null?void 0:c.Fa()}catch(d){}}c=
await _ds.Su(_ds.A().toString());a=new _ds.YP;try{let d,e;await a.Zb({url:"https://developers.google.com/profile/badges/recognitions/learnings",profileId:(e=(d=b)==null?void 0:d.Ca())!=null?e:"",eventType:"EVENT_TYPE_LEARNING",event:{title:document.title,awardingResource:c}})}catch(d){}}}},W$=function(){const a=document.querySelector("devsite-user#devsite-user");return a!=null&&a.hasAttribute("enable-profiles")},lwa=class extends iwa{constructor(){super(new Mva);this.eventHandler.listen(this,"google-codelab-completed",
()=>{V$(this)});document.addEventListener("devsite-award-eligible",()=>{V$(this)})}async nf(){if(W$()){var a=void 0;if(await (await _ds.u()).isSignedIn()){var b=new _ds.JQ;try{var c;a=(c=await _ds.yQ(b,new _ds.NN))==null?void 0:c.Fa()}catch(d){}}b=_ds.Ru(await _ds.Su(_ds.A().toString()));c=new _ds.cx;try{let d,e;await c.nf({awardingUrl:_ds.Gm(_ds.Fm(_ds.A())),badgePath:"https://developers.google.com/profile/badges/recognitions/learnings",resourceName:b,obfuscatedProfileId:(e=(d=a)==null?void 0:d.Ca())!=
null?e:void 0})}catch(d){}}}};try{customElements.define("google-codelab",lwa)}catch(a){console.warn("Unrecognized DevSite custom element - GoogleDevCodelab",a)};})(_ds_www);
