(function(_ds){var window=this;var C4=function(a,b){_ds.Ko(a,"transform","translate3d("+b+"px,0px,0px)")};var F4=function(a){a.j=D4(a,".devsite-top-logo-row-wrapper-wrapper");a.g=D4(a,".devsite-collapsible-section");a.o=D4(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",`${a.j}`);a.setAttribute("bottom-row--height",`${a.g}`);a.setAttribute("bottom-tabs--height",`${a.o}`);a.style.setProperty("--devsite-js-top-row--height",`${a.j}px`);a.style.setProperty("--devsite-js-bottom-row--height",`${a.g}px`);a.style.setProperty("--devsite-js-bottom-tabs--height",`${a.o}px`);E4(a);a.h.resolve()},E4=
function(a){const b=a.querySelector(".devsite-collapsible-section");a.offset>=a.g&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.offset<a.g-a.o&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.offset!==a.ra&&(_ds.Ko(b,"transform",`translate3d(0, -${a.offset}px, 0)`),G4(a),a.ra=a.offset);document.body.style.setProperty("--devsite-js-header-height",`${a.ea()}px`)},qna=function(a){var b=a.querySelector(".devsite-top-logo-row-middle");
const c=a.querySelector("devsite-search"),d=a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.C(a.oa);a.ma&&window.cancelAnimationFrame(a.ma);c.removeAttribute("transition");a.removeAttribute("search-expanded");var e=new _ds.Uk(b.offsetWidth,b.offsetHeight);b=new _ds.Uk(c.offsetWidth,c.offsetHeight);var f=_ds.$o(c),g=document.documentElement.getAttribute("dir")==="rtl"?1:-1,h=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*g;var k=(f=a.hasAttribute("search-active"))?
e:0,l=f?h:1;_ds.Ko(d,{opacity:1,width:`${b.width}px`,height:`${b.height}px`});C4(c,a.hasAttribute("search-active")?0:e);_ds.Ho(a.oa,d,_ds.Wl,()=>{const m=a.querySelector("devsite-search"),n=a.querySelector(".devsite-search-background");n&&(n.style.opacity="0");m&&(m.removeAttribute("transition"),C4(m,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.ma=window.requestAnimationFrame(()=>{c.setAttribute("transition","");_ds.Ko(d,"transform",
"scale3d("+l+",1,1)");C4(c,k)})}},rna=async function(a,b){if(a.hasAttribute("billboard")){var c=a.querySelector("devsite-search"),d=a.querySelector("devsite-search input.devsite-search-query");a=a.querySelector(".devsite-header-billboard-search devsite-search");var e=a==null?void 0:a.querySelector("input.devsite-search-query");c&&d&&a&&e&&(b?(c.removeAttribute("disabled"),document.activeElement===e&&(await _ds.Um(),d.focus()),a.setAttribute("disabled","")):(a.removeAttribute("disabled"),document.activeElement===
d&&e.focus(),c.setAttribute("disabled","")))}},sna=function(a){a.eventHandler.listen(a,"devsite-search-toggle",b=>{b=b.getBrowserEvent();_ds.Tl(b.target,null,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",""):a.removeAttribute("search-active"))});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{document.body.removeAttribute("devsite-book-nav--open")});a.eventHandler.listen(window,"resize",()=>{H4(a)});a.eventHandler.listen(document.body,["devsite-page-loaded",
"devsite-content-updated"],()=>{H4(a)});a.eventHandler.listen(a,"click",b=>{b.defaultPrevented||b.target.getAttribute("id")!=="devsite-hamburger-menu"||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})},I4=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){const b=document.createElement("div");b.classList.add("devsite-search-background");
b.style.opacity="1";a.appendChild(b)}},G4=function(a){a.g===0?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},H4=function(a){window.requestAnimationFrame(()=>{a.va.Ua()})},D4=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},J4=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=
0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},K4=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.updated=!0,_ds.Mk(a,c,b))},tna=class extends _ds.Nk{constructor(){super(...arguments);this.eventHandler=new _ds.B;this.ra=-1;this.oa=new _ds.B;this.ma=0;this.qa=new MutationObserver(()=>{F4(this)});this.va=new _ds.Vg(()=>{F4(this);G4(this)},15);this.authUser=void 0;this.offset=this.o=this.g=this.j=0;this.updated=!1;this.h=new _ds.Mg}static get observedAttributes(){return["offset",
"search-active","bottom-row--hidden"]}attributeChangedCallback(a,b,c){switch(a){case "offset":this.offset=Number(this.getAttribute("offset")||"")||0;E4(this);break;case "search-active":qna(this);break;case "bottom-row--hidden":a=c!==null,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),rna(this,a)}}connectedCallback(){sna(this);I4(this);G4(this);
F4(this);this.qa.observe(this,{childList:!0,subtree:!0});E4(this);const a=_ds.A();this.authUser=_ds.um(_ds.vm(a.href),"authuser")}disconnectedCallback(){_ds.C(this.eventHandler);this.qa.disconnect()}ea(){return this.j+this.g-this.offset}ua(){return this.j+this.g}Qb(a){this.h&&this.h.resolve();this.h=new _ds.Mg;this.updated=!1;if(a){K4(this,a,".devsite-header-upper-tabs");K4(this,a,".devsite-collapsible-section");K4(this,a,".devsite-product-name-wrapper");K4(this,a,"devsite-language-selector");K4(this,
a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&J4(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(J4(c,b),c=_ds.A(),c=_ds.um(_ds.vm(c.href),"authuser"),c!==this.authUser&&(this.authUser=c,b.refresh()));_ds.Mk(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.Mk(this,this.querySelector(".devsite-header-link"),
a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.updated&&a&&(_ds.Bl(this),this.appendChild(a));I4(this);H4(this)}async ready(){return this.h.promise}};try{customElements.define("devsite-header",tna)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
