(function(_ds){var window=this;var Cja=function(){return(0,_ds.Q)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},Dja=function(){return(0,_ds.Q)('<div class="devsite-book-nav-blur"></div>')},Eja=function(a){a=a.mA;a=_ds.sU(new _ds.qw("{NUMBER_OF_MATCHING_DESCENDANTS,plural,=1{{XXX_1} match}other{{XXX_2} matches}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.T(_ds.Hu(1)),XXX_2:_ds.T(_ds.Hu(a))});return(0,_ds.Q)('<span class="devsite-nav-filter-match-count"> (<mark>'+
a+"</mark>)</span>")};var Fja="onpointerover"in window?"pointerover":"mouseover",b1=function(a){const b=a.querySelectorAll(".devsite-nav-item").length>0,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.Kk(a,"visually-hidden","",c))},Gja=async function(a){a.classList.contains("hide-collapsed-panel")&&a.classList.remove("hide-collapsed-panel");var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;const c=b?document.documentElement.scrollTop/b:
0;_ds.Ho(a.eventHandler,a,_ds.Wl,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.o.removeAttribute("animatable")});_ds.Kk(a,"animatable","");b=_ds.Qf(a.v`animatable`);b(a.background,"animatable","");b(a.o,"animatable","");a.hasAttribute("collapsed")?(_ds.Kk(a,"aria-label","Hide side navigation",a.g),_ds.Kk(a,"data-title","Hide side navigation",a.g),a.removeAttribute("collapsed"),_ds.sX(a.g,"expanded","true"),c1(a,"Expanded book nav")):(_ds.Kk(a,"aria-label","Show side navigation",
a.g),_ds.Kk(a,"data-title","Show side navigation",a.g),_ds.Kk(a,"collapsed",""),_ds.sX(a.g,"expanded","false"),c1(a,"Collapsed book nav"),_ds.Ho(a.eventHandler,a,_ds.Wl,()=>{a.classList.add("hide-collapsed-panel")}));await _ds.Um();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},Ija=function(a){a.eventHandler.listen(a,"click",b=>void d1(a,b));a.eventHandler.listen(a,"keypress",b=>{b.key==="Enter"&&d1(a,b)});a.eventHandler.listen(a,
[Fja,"focusin"],b=>void Hja(a,b));a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{a.j&&(e1(a,"_book")?a.removeAttribute("top-level-nav"):_ds.Kk(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",()=>void a.ua.Ua());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.ua.Ua()});a.eventHandler.listen(a,"scroll",()=>{_ds.Kk(a,"user-scrolled","")});a.eventHandler.listen(a.g,"click",()=>{a.Ea.Ua()});a.h&&(a.eventHandler.listen(a.h,"keyup",()=>void a.va.Ua()),
a.eventHandler.listen(a.h,"focus",()=>void f1(a,"focus")));a.ma&&a.eventHandler.listen(a.ma,["click","keydown"],b=>{if(b.type==="click"||b.key==="Enter"||b.key==="Escape"){a.h&&(a.h.value="",a.h.focus());let c;(c=a.ma)==null||c.classList.add("hidden");g1(a);h1(a);f1(a,b.type)}})},i1=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.ea=new Set(b);if(!_ds.A().hash&&c)Jja(a,a.ea);else{c=new _ds.pX;for(const d of a.ea)_ds.oX(c,d)}},j1=async function(a){const b=await _ds.u();
for(const c of a.ea)b.unregisterIntersectionForElement(c)},d1=function(a,b){if(!b.defaultPrevented){var c=b.target;c.getAttribute("id")==="devsite-close-nav"&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.Kk(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&e1(a,d)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=
c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=b.target,g,h;if(!((g=f)==null?0:(h=g.closest(".devsite-nav-title"))==null?0:h.hasAttribute("href"))){for(b=b.type==="click"||b.type==="touchend";f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&_ds.Kk(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||
(a.j&&(d=a.j.querySelector("[menu=_book]"))&&d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},Hja=function(a,b){b.defaultPrevented||(b=_ds.Sl(b.target,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0),b!==a&&_ds.Hf(b,_ds.Nm(b.href).href))},f1=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",
{detail:{category:"Site-Wide Custom Events",action:b,label:b==="focus"?"devsite-book-nav-filter input":"devsite-book-nav-filter filter-clear-button"},bubbles:!0}))},k1=function(a){a.oa=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},m1=function(a){const b=_ds.A().searchParams.get("nf");a.h&&b&&(a.h.value=b,l1(a))},l1=function(a){if(a.oa.length){g1(a);h1(a);var b,c,d=(b=a.h)==null?void 0:(c=b.value)==null?void 0:
c.trim().toLowerCase();if(d){var e;(e=a.ma)==null||e.classList.remove("hidden");for(const g of a.oa){var f=g.querySelectorAll(".devsite-nav-text");a=g.classList.contains("devsite-nav-expandable");e=c=!1;b=0;let h,k,l;const m=((l=(h=g)==null?void 0:(k=h.getAttribute("data-synonyms"))==null?void 0:k.split(","))!=null?l:[]).some(r=>r.toLowerCase().includes(d));let n,q;if(d&&a&&(m||((n=g.querySelector(".devsite-nav-text"))==null?0:(q=n.textContent)==null?0:q.toLowerCase().includes(d))))e=c=!0;else for(const r of f){let y,
E,H,K;f=((K=(y=r)==null?void 0:(E=y.parentElement)==null?void 0:(H=E.getAttribute("data-synonyms"))==null?void 0:H.split(","))!=null?K:[]).some(I=>I.toLowerCase().includes(d));if(d){let I;if(f||((I=r.textContent)==null?0:I.toLowerCase().includes(d)))c=!0,++b}}if(c===!0){g.classList.remove("hidden");if(e){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(const r of c){r.classList.remove("hidden");let y,E,H,K;c=((K=(y=r)==null?void 0:(E=y.parentElement)==null?void 0:(H=E.getAttribute("data-synonyms"))==
null?void 0:H.split(","))!=null?K:[]).some(P=>P.toLowerCase().includes(d));let I;d&&(c||((I=r.textContent)==null?0:I.toLowerCase().includes(d)))&&++b}}Kja(g,d)}a&&b>0&&Lja(g,b)}}else(f=a.ma)==null||f.classList.add("hidden")}},g1=function(a){for(const b of a.oa){let c;b.classList.toggle("hidden",!((c=a.h)==null||!c.value))}},h1=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];
for(const c of a){a=c.parentElement;let d;b=(d=a)==null?void 0:d.textContent;a&&b&&_ds.Of(a,_ds.pg(b))}}},Kja=function(a,b){if(a=a.querySelector(".devsite-nav-text")){var c,d=(c=a.textContent)==null?void 0:c.replace(new RegExp(`(${b})`,"ig"),"<mark>$1</mark>");d&&_ds.Of(a,_ds.pg(d))}},Lja=function(a,b){if(a=a.querySelector(".devsite-nav-text"))b=_ds.J(Eja,{mA:b}),a.appendChild(b)},Jja=async function(a,b){if(a.connected){var c=await _ds.u(),d=new _ds.pX,e=f=>{f=f.target;_ds.oX(d,f);a.ea.delete(f);
c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,e)}catch(g){e({target:f})}}},e1=function(a,b){let c=!1;if(a.j)for(const d of a.j.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.Kk(a,"hidden","",d);return c},n1=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active"),c.removeAttribute("aria-selected");a=_ds.an(_ds.A().pathname);a=`[href="${_ds.Nm(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active"),_ds.sX(c,"selected","true")},o1=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},Mja=async function(a){a.connected&&(a.removeAttribute("user-scrolled"),await _ds.Um(),await p1(a),await a.xa,
await _ds.u(),await _ds.Um(),await p1(a))},p1=async function(a){if(a.connected&&a.j){await _ds.u();var b=a.j.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await Nja(a,b))}},Nja=async function(a,b){if(a.connected){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.To(b,a,!0).y;await _ds.Um();c&&_ds.Kk(a,"user-scrolled","")}},c1=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},
bubbles:!0}))},q1=class extends _ds.Nk{static get observedAttributes(){return["collapsed","fixed","hidden"]}constructor(){super();this.connected=!1;this.ma=this.h=this.qa=this.j=null;this.oa=[];this.eventHandler=new _ds.B;this.ra=()=>{};this.ea=new Set;_ds.Jk(this,this.v`animatable`,this.v`aria-expanded`,this.v`aria-label`,this.v`collapsed`,this.v`data-title`,this.v`fixed`,this.v`has-book-nav`,this.v`hidden`,this.v`top-level-nav`,this.v`user-scrolled`,this.v`visually-hidden`);this.background=document.createElement("div");
this.background.classList.add("devsite-book-nav-bg");this.g=_ds.J(Cja);this.o=_ds.J(Dja);this.xa=new Promise(a=>{this.ra=a});this.ua=new _ds.Vg(()=>{this.connected&&b1(this)},20);this.va=new _ds.Vg(()=>{l1(this)},20);this.Ea=new _ds.Vg(()=>{Gja(this)},100)}async connectedCallback(){this.connected=!0;_ds.Cl(this.background,this);this.hasAttribute("hidden")&&(_ds.Kk(this,"hidden","",this.g),_ds.Kk(this,"hidden","",this.o));let a;(a=this.parentElement)==null||a.insertBefore(this.g,this.nextSibling);
_ds.Kk(this,"aria-label","Hide side navigation",this.g);_ds.Kk(this,"data-title","Hide side navigation",this.g);_ds.Kk(this,"aria-expanded","true",this.g);let b;(b=this.parentElement)==null||b.insertBefore(this.o,this.nextSibling);if(this.qa=this.querySelector(".devsite-book-nav-filter"))this.h=this.qa.querySelector("input[type=text]"),this.ma=this.qa.querySelector(".filter-clear-button"),k1(this),m1(this);b1(this);Ija(this);await this.init();i1(this)}disconnectedCallback(){this.connected=!1;_ds.C(this.eventHandler);
j1(this);this.ea.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.Kk(this,"visually-hidden","",a);a=[this.background,this.g,this.o];for(const b of a)b&&_ds.El(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.o.removeAttribute("animatable");this.o.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){a==="hidden"&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":
"devsite-element-visible",{bubbles:!0}));if(a==="hidden"||a==="collapsed"){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.Kk(this,"has-book-nav","",b))}if(a==="fixed"||a==="hidden"||a==="collapsed"){b=this.hasAttribute(a);const c=[this.background,this.g,this.o];for(const d of c)d&&(b?_ds.Kk(this,a,"",d):d.removeAttribute(a))}a==="fixed"&&this.ra()}async init(a=!0){if(this.connected){this.o.style.setProperty("--devsite-js-book-nav-scrollbar-width",
`${this.offsetWidth-this.clientWidth}px`);this.j=this.querySelector(".devsite-mobile-nav-bottom");_ds.Kk(this,"top-level-nav","");this.j&&this.j.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");this.children.length===0&&_ds.Kk(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.Kk(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(n1(this),o1(this),await Mja(this)):(await _ds.Um(),await p1(this))}}async Qb(a){a?
(a=a.querySelector("nav")||null,n1(this,a),o1(this,a),a&&(await j1(this),this.ea.clear(),i1(this,a,!1)),_ds.Mk(this,this.querySelector("nav"),a)):_ds.Bl(this);k1(this);if(this.h){this.h.value="";let b;(b=this.ma)==null||b.classList.add("hidden");m1(this)}await _ds.Um();await this.init(!1)}};q1.prototype.updateContent=q1.prototype.Qb;q1.prototype.attributeChangedCallback=q1.prototype.attributeChangedCallback;q1.prototype.disconnectedCallback=q1.prototype.disconnectedCallback;
q1.prototype.connectedCallback=q1.prototype.connectedCallback;try{customElements.define("devsite-book-nav",q1)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
